version: "3.8"

services:

  nats:
    image: nats:2.10
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222" # Monitoring
    networks:
      - app-net

volumes:
  mongo-data:

networks:
  app-net: