// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: purchase.proto

package purchasepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuyTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // ID пользователя
	LotteryId     int64                  `protobuf:"varint,2,opt,name=lottery_id,json=lotteryId,proto3" json:"lottery_id,omitempty"` // ID лотереи
	Numbers       []int32                `protobuf:"varint,3,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`               // 5 чисел, которые пользователь вводит
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyTicketRequest) Reset() {
	*x = BuyTicketRequest{}
	mi := &file_purchase_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyTicketRequest) ProtoMessage() {}

func (x *BuyTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyTicketRequest.ProtoReflect.Descriptor instead.
func (*BuyTicketRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{0}
}

func (x *BuyTicketRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BuyTicketRequest) GetLotteryId() int64 {
	if x != nil {
		return x.LotteryId
	}
	return 0
}

func (x *BuyTicketRequest) GetNumbers() []int32 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

type BuyTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TicketId      int64                  `protobuf:"varint,3,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`    // ID для билета
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // ID пользователя, который купил билет
	LotteryId     int64                  `protobuf:"varint,5,opt,name=lottery_id,json=lotteryId,proto3" json:"lottery_id,omitempty"` // ID лотереи, для которой куплен билет
	Numbers       []int32                `protobuf:"varint,6,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`               // Числа, которые были выбраны пользователем
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyTicketResponse) Reset() {
	*x = BuyTicketResponse{}
	mi := &file_purchase_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyTicketResponse) ProtoMessage() {}

func (x *BuyTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyTicketResponse.ProtoReflect.Descriptor instead.
func (*BuyTicketResponse) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{1}
}

func (x *BuyTicketResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BuyTicketResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BuyTicketResponse) GetTicketId() int64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *BuyTicketResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BuyTicketResponse) GetLotteryId() int64 {
	if x != nil {
		return x.LotteryId
	}
	return 0
}

func (x *BuyTicketResponse) GetNumbers() []int32 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

var File_purchase_proto protoreflect.FileDescriptor

const file_purchase_proto_rawDesc = "" +
	"\n" +
	"\x0epurchase.proto\x12\n" +
	"purchasepb\"d\n" +
	"\x10BuyTicketRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"lottery_id\x18\x02 \x01(\x03R\tlotteryId\x12\x18\n" +
	"\anumbers\x18\x03 \x03(\x05R\anumbers\"\xb6\x01\n" +
	"\x11BuyTicketResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tticket_id\x18\x03 \x01(\x03R\bticketId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"lottery_id\x18\x05 \x01(\x03R\tlotteryId\x12\x18\n" +
	"\anumbers\x18\x06 \x03(\x05R\anumbers2[\n" +
	"\x0fPurchaseService\x12H\n" +
	"\tBuyTicket\x12\x1c.purchasepb.BuyTicketRequest\x1a\x1d.purchasepb.BuyTicketResponseB4Z2github.com/CharLottery/proto/purchasepb;purchasepbb\x06proto3"

var (
	file_purchase_proto_rawDescOnce sync.Once
	file_purchase_proto_rawDescData []byte
)

func file_purchase_proto_rawDescGZIP() []byte {
	file_purchase_proto_rawDescOnce.Do(func() {
		file_purchase_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_purchase_proto_rawDesc), len(file_purchase_proto_rawDesc)))
	})
	return file_purchase_proto_rawDescData
}

var file_purchase_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_purchase_proto_goTypes = []any{
	(*BuyTicketRequest)(nil),  // 0: purchasepb.BuyTicketRequest
	(*BuyTicketResponse)(nil), // 1: purchasepb.BuyTicketResponse
}
var file_purchase_proto_depIdxs = []int32{
	0, // 0: purchasepb.PurchaseService.BuyTicket:input_type -> purchasepb.BuyTicketRequest
	1, // 1: purchasepb.PurchaseService.BuyTicket:output_type -> purchasepb.BuyTicketResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_purchase_proto_init() }
func file_purchase_proto_init() {
	if File_purchase_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_purchase_proto_rawDesc), len(file_purchase_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_purchase_proto_goTypes,
		DependencyIndexes: file_purchase_proto_depIdxs,
		MessageInfos:      file_purchase_proto_msgTypes,
	}.Build()
	File_purchase_proto = out.File
	file_purchase_proto_goTypes = nil
	file_purchase_proto_depIdxs = nil
}
