// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: lottery.proto

package lotterypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lottery struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Prize            string                 `protobuf:"bytes,4,opt,name=prize,proto3" json:"prize,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	AvailableTickets int64                  `protobuf:"varint,6,opt,name=available_tickets,json=availableTickets,proto3" json:"available_tickets,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Lottery) Reset() {
	*x = Lottery{}
	mi := &file_lottery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lottery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lottery) ProtoMessage() {}

func (x *Lottery) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lottery.ProtoReflect.Descriptor instead.
func (*Lottery) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{0}
}

func (x *Lottery) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Lottery) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Lottery) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Lottery) GetPrize() string {
	if x != nil {
		return x.Prize
	}
	return ""
}

func (x *Lottery) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Lottery) GetAvailableTickets() int64 {
	if x != nil {
		return x.AvailableTickets
	}
	return 0
}

type CreateLotteryRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Title            string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description      string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Prize            string                 `protobuf:"bytes,3,opt,name=prize,proto3" json:"prize,omitempty"`
	AvailableTickets int64                  `protobuf:"varint,4,opt,name=available_tickets,json=availableTickets,proto3" json:"available_tickets,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateLotteryRequest) Reset() {
	*x = CreateLotteryRequest{}
	mi := &file_lottery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLotteryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLotteryRequest) ProtoMessage() {}

func (x *CreateLotteryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLotteryRequest.ProtoReflect.Descriptor instead.
func (*CreateLotteryRequest) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLotteryRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateLotteryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateLotteryRequest) GetPrize() string {
	if x != nil {
		return x.Prize
	}
	return ""
}

func (x *CreateLotteryRequest) GetAvailableTickets() int64 {
	if x != nil {
		return x.AvailableTickets
	}
	return 0
}

type CreateLotteryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lottery       *Lottery               `protobuf:"bytes,1,opt,name=lottery,proto3" json:"lottery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLotteryResponse) Reset() {
	*x = CreateLotteryResponse{}
	mi := &file_lottery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLotteryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLotteryResponse) ProtoMessage() {}

func (x *CreateLotteryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLotteryResponse.ProtoReflect.Descriptor instead.
func (*CreateLotteryResponse) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLotteryResponse) GetLottery() *Lottery {
	if x != nil {
		return x.Lottery
	}
	return nil
}

type GetLotteryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLotteryRequest) Reset() {
	*x = GetLotteryRequest{}
	mi := &file_lottery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLotteryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLotteryRequest) ProtoMessage() {}

func (x *GetLotteryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLotteryRequest.ProtoReflect.Descriptor instead.
func (*GetLotteryRequest) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{3}
}

func (x *GetLotteryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetLotteryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lottery       *Lottery               `protobuf:"bytes,1,opt,name=lottery,proto3" json:"lottery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLotteryResponse) Reset() {
	*x = GetLotteryResponse{}
	mi := &file_lottery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLotteryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLotteryResponse) ProtoMessage() {}

func (x *GetLotteryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLotteryResponse.ProtoReflect.Descriptor instead.
func (*GetLotteryResponse) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{4}
}

func (x *GetLotteryResponse) GetLottery() *Lottery {
	if x != nil {
		return x.Lottery
	}
	return nil
}

type ListLotteriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLotteriesRequest) Reset() {
	*x = ListLotteriesRequest{}
	mi := &file_lottery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLotteriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLotteriesRequest) ProtoMessage() {}

func (x *ListLotteriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLotteriesRequest.ProtoReflect.Descriptor instead.
func (*ListLotteriesRequest) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{5}
}

type ListLotteriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lotteries     []*Lottery             `protobuf:"bytes,1,rep,name=lotteries,proto3" json:"lotteries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLotteriesResponse) Reset() {
	*x = ListLotteriesResponse{}
	mi := &file_lottery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLotteriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLotteriesResponse) ProtoMessage() {}

func (x *ListLotteriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLotteriesResponse.ProtoReflect.Descriptor instead.
func (*ListLotteriesResponse) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{6}
}

func (x *ListLotteriesResponse) GetLotteries() []*Lottery {
	if x != nil {
		return x.Lotteries
	}
	return nil
}

var File_lottery_proto protoreflect.FileDescriptor

const file_lottery_proto_rawDesc = "" +
	"\n" +
	"\rlottery.proto\x12\tlotterypb\"\xac\x01\n" +
	"\aLottery\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05prize\x18\x04 \x01(\tR\x05prize\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12+\n" +
	"\x11available_tickets\x18\x06 \x01(\x03R\x10availableTickets\"\x91\x01\n" +
	"\x14CreateLotteryRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05prize\x18\x03 \x01(\tR\x05prize\x12+\n" +
	"\x11available_tickets\x18\x04 \x01(\x03R\x10availableTickets\"E\n" +
	"\x15CreateLotteryResponse\x12,\n" +
	"\alottery\x18\x01 \x01(\v2\x12.lotterypb.LotteryR\alottery\"#\n" +
	"\x11GetLotteryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"B\n" +
	"\x12GetLotteryResponse\x12,\n" +
	"\alottery\x18\x01 \x01(\v2\x12.lotterypb.LotteryR\alottery\"\x16\n" +
	"\x14ListLotteriesRequest\"I\n" +
	"\x15ListLotteriesResponse\x120\n" +
	"\tlotteries\x18\x01 \x03(\v2\x12.lotterypb.LotteryR\tlotteries2\x83\x02\n" +
	"\x0eLotteryService\x12R\n" +
	"\rCreateLottery\x12\x1f.lotterypb.CreateLotteryRequest\x1a .lotterypb.CreateLotteryResponse\x12I\n" +
	"\n" +
	"GetLottery\x12\x1c.lotterypb.GetLotteryRequest\x1a\x1d.lotterypb.GetLotteryResponse\x12R\n" +
	"\rListLotteries\x12\x1f.lotterypb.ListLotteriesRequest\x1a .lotterypb.ListLotteriesResponseB2Z0github.com/CharLottery/proto/lotterypb;lotterypbb\x06proto3"

var (
	file_lottery_proto_rawDescOnce sync.Once
	file_lottery_proto_rawDescData []byte
)

func file_lottery_proto_rawDescGZIP() []byte {
	file_lottery_proto_rawDescOnce.Do(func() {
		file_lottery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lottery_proto_rawDesc), len(file_lottery_proto_rawDesc)))
	})
	return file_lottery_proto_rawDescData
}

var file_lottery_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_lottery_proto_goTypes = []any{
	(*Lottery)(nil),               // 0: lotterypb.Lottery
	(*CreateLotteryRequest)(nil),  // 1: lotterypb.CreateLotteryRequest
	(*CreateLotteryResponse)(nil), // 2: lotterypb.CreateLotteryResponse
	(*GetLotteryRequest)(nil),     // 3: lotterypb.GetLotteryRequest
	(*GetLotteryResponse)(nil),    // 4: lotterypb.GetLotteryResponse
	(*ListLotteriesRequest)(nil),  // 5: lotterypb.ListLotteriesRequest
	(*ListLotteriesResponse)(nil), // 6: lotterypb.ListLotteriesResponse
}
var file_lottery_proto_depIdxs = []int32{
	0, // 0: lotterypb.CreateLotteryResponse.lottery:type_name -> lotterypb.Lottery
	0, // 1: lotterypb.GetLotteryResponse.lottery:type_name -> lotterypb.Lottery
	0, // 2: lotterypb.ListLotteriesResponse.lotteries:type_name -> lotterypb.Lottery
	1, // 3: lotterypb.LotteryService.CreateLottery:input_type -> lotterypb.CreateLotteryRequest
	3, // 4: lotterypb.LotteryService.GetLottery:input_type -> lotterypb.GetLotteryRequest
	5, // 5: lotterypb.LotteryService.ListLotteries:input_type -> lotterypb.ListLotteriesRequest
	2, // 6: lotterypb.LotteryService.CreateLottery:output_type -> lotterypb.CreateLotteryResponse
	4, // 7: lotterypb.LotteryService.GetLottery:output_type -> lotterypb.GetLotteryResponse
	6, // 8: lotterypb.LotteryService.ListLotteries:output_type -> lotterypb.ListLotteriesResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_lottery_proto_init() }
func file_lottery_proto_init() {
	if File_lottery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lottery_proto_rawDesc), len(file_lottery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lottery_proto_goTypes,
		DependencyIndexes: file_lottery_proto_depIdxs,
		MessageInfos:      file_lottery_proto_msgTypes,
	}.Build()
	File_lottery_proto = out.File
	file_lottery_proto_goTypes = nil
	file_lottery_proto_depIdxs = nil
}
