# Используем официальный образ Go
FROM golang:1.21-alpine

# Устанавливаем зависимости
RUN apk update && apk add --no-cache git

# Создаем рабочую директорию
WORKDIR /app

# Копируем go.mod и go.sum для установки зависимостей
COPY go.mod go.sum ./
RUN go mod download

# Копируем остальные файлы проекта
COPY . .


COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
# Собираем приложение
RUN go build -o lottery_service ./cmd/main.go
COPY ../proto ./proto
RUN go mod edit -replace=github.com/CharLottery/proto=./proto && go mod download

# Указываем порт
EXPOSE 50055

# Команда запуска
ENTRYPOINT ["/entrypoint.sh"]

CMD ["./lottery_service"]
